dxl_yaw_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 1.0
    motor:
        id: 2
        init: 492
        min: 0
        max: 1023
dxl_pitch_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 1.0
    motor:
        id: 3
        init: 488
        min: 0
        max: 1023
